title: 'Cats Forum'
subtitle: 'Find and share images and videos of your internet cats'
url: "stupefied-galileo-6dfad7.netlify.com"

markdown: kramdown

kramdown:
  hard_wrap: true
  input: GFM

theme: jekyll-theme-minimal
